FROM amazoncorretto:15
WORKDIR /home/ec2-user/dockme
RUN ls -lAh
RUN yum update -y \
&& yum install -y autoconf aclocal automake make \
&& yum install -y libtool \
&& yum install -y libjpeg-devel libpng-devel libtiff-devel zlib-devel \
&& yum install -y wget file gzip awscli vim iotop htop

#RUN yum install python
RUN yum install -y python3.x86_64
# install telethon
COPY pip_requirements.txt .
RUN pip3 install -r pip_requirements.txt

# Install our files
RUN yum install -y xorg-x11-server-Xvfb which \
&& yum install -y libXext.x86_64 \
&& yum install -y libXrender.x86_64 \
&& yum install -y libXtst.x86_64

# Utilities
## these are examples
COPY src src 
COPY scripts ./scripts 
COPY configs ./configs 

ENTRYPOINT ["/bin/bash"]
CMD ["/home/ec2-user/dockme/scripts/entry_point.sh"]