version: 0.2

phases:
  build:
    commands:
       - docker build . -t prod-trader
       - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 240840959695.dkr.ecr.ap-northeast-1.amazonaws.com && docker tag prod-trader 240840959695.dkr.ecr.ap-northeast-1.amazonaws.com/worker:latest && docker push 240840959695.dkr.ecr.ap-northeast-1.amazonaws.com/worker:latest
